// <auto-generated />
using System;
using BattleCottage.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BattleCottage.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20231002181133_Somechanges")]
    partial class Somechanges
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BattleCottage.Core.Entities.Game", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("BackgroundImage")
                        .HasColumnType("text");

                    b.Property<DateTime>("DateAdded")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Games");
                });

            modelBuilder.Entity("BattleCottage.Core.Entities.GameMode", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateAdded")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("GameModes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DateAdded = new DateTime(2023, 10, 2, 18, 11, 33, 588, DateTimeKind.Utc).AddTicks(9149),
                            DateUpdated = new DateTime(2023, 10, 2, 18, 11, 33, 588, DateTimeKind.Utc).AddTicks(9150),
                            Name = "PvP"
                        },
                        new
                        {
                            Id = 2,
                            DateAdded = new DateTime(2023, 10, 2, 18, 11, 33, 588, DateTimeKind.Utc).AddTicks(9151),
                            DateUpdated = new DateTime(2023, 10, 2, 18, 11, 33, 588, DateTimeKind.Utc).AddTicks(9151),
                            Name = "PvE"
                        });
                });

            modelBuilder.Entity("BattleCottage.Core.Entities.GameRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateAdded")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("GameRoles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DateAdded = new DateTime(2023, 10, 2, 18, 11, 33, 588, DateTimeKind.Utc).AddTicks(9302),
                            DateUpdated = new DateTime(2023, 10, 2, 18, 11, 33, 588, DateTimeKind.Utc).AddTicks(9303),
                            Name = "Tank"
                        },
                        new
                        {
                            Id = 2,
                            DateAdded = new DateTime(2023, 10, 2, 18, 11, 33, 588, DateTimeKind.Utc).AddTicks(9304),
                            DateUpdated = new DateTime(2023, 10, 2, 18, 11, 33, 588, DateTimeKind.Utc).AddTicks(9304),
                            Name = "Healer"
                        },
                        new
                        {
                            Id = 3,
                            DateAdded = new DateTime(2023, 10, 2, 18, 11, 33, 588, DateTimeKind.Utc).AddTicks(9305),
                            DateUpdated = new DateTime(2023, 10, 2, 18, 11, 33, 588, DateTimeKind.Utc).AddTicks(9306),
                            Name = "DPS"
                        },
                        new
                        {
                            Id = 4,
                            DateAdded = new DateTime(2023, 10, 2, 18, 11, 33, 588, DateTimeKind.Utc).AddTicks(9307),
                            DateUpdated = new DateTime(2023, 10, 2, 18, 11, 33, 588, DateTimeKind.Utc).AddTicks(9307),
                            Name = "Top Lane"
                        },
                        new
                        {
                            Id = 5,
                            DateAdded = new DateTime(2023, 10, 2, 18, 11, 33, 588, DateTimeKind.Utc).AddTicks(9308),
                            DateUpdated = new DateTime(2023, 10, 2, 18, 11, 33, 588, DateTimeKind.Utc).AddTicks(9308),
                            Name = "Bottom Lane"
                        },
                        new
                        {
                            Id = 6,
                            DateAdded = new DateTime(2023, 10, 2, 18, 11, 33, 588, DateTimeKind.Utc).AddTicks(9309),
                            DateUpdated = new DateTime(2023, 10, 2, 18, 11, 33, 588, DateTimeKind.Utc).AddTicks(9310),
                            Name = "Mid Lane"
                        },
                        new
                        {
                            Id = 7,
                            DateAdded = new DateTime(2023, 10, 2, 18, 11, 33, 588, DateTimeKind.Utc).AddTicks(9311),
                            DateUpdated = new DateTime(2023, 10, 2, 18, 11, 33, 588, DateTimeKind.Utc).AddTicks(9311),
                            Name = "Jungle"
                        },
                        new
                        {
                            Id = 8,
                            DateAdded = new DateTime(2023, 10, 2, 18, 11, 33, 588, DateTimeKind.Utc).AddTicks(9312),
                            DateUpdated = new DateTime(2023, 10, 2, 18, 11, 33, 588, DateTimeKind.Utc).AddTicks(9312),
                            Name = "Support"
                        },
                        new
                        {
                            Id = 9,
                            DateAdded = new DateTime(2023, 10, 2, 18, 11, 33, 588, DateTimeKind.Utc).AddTicks(9313),
                            DateUpdated = new DateTime(2023, 10, 2, 18, 11, 33, 588, DateTimeKind.Utc).AddTicks(9314),
                            Name = "Entry Fragger"
                        },
                        new
                        {
                            Id = 10,
                            DateAdded = new DateTime(2023, 10, 2, 18, 11, 33, 588, DateTimeKind.Utc).AddTicks(9315),
                            DateUpdated = new DateTime(2023, 10, 2, 18, 11, 33, 588, DateTimeKind.Utc).AddTicks(9315),
                            Name = "ReFragger"
                        },
                        new
                        {
                            Id = 11,
                            DateAdded = new DateTime(2023, 10, 2, 18, 11, 33, 588, DateTimeKind.Utc).AddTicks(9316),
                            DateUpdated = new DateTime(2023, 10, 2, 18, 11, 33, 588, DateTimeKind.Utc).AddTicks(9317),
                            Name = "Strategy Caller"
                        },
                        new
                        {
                            Id = 12,
                            DateAdded = new DateTime(2023, 10, 2, 18, 11, 33, 588, DateTimeKind.Utc).AddTicks(9317),
                            DateUpdated = new DateTime(2023, 10, 2, 18, 11, 33, 588, DateTimeKind.Utc).AddTicks(9318),
                            Name = "Lurker"
                        },
                        new
                        {
                            Id = 13,
                            DateAdded = new DateTime(2023, 10, 2, 18, 11, 33, 588, DateTimeKind.Utc).AddTicks(9319),
                            DateUpdated = new DateTime(2023, 10, 2, 18, 11, 33, 588, DateTimeKind.Utc).AddTicks(9319),
                            Name = "Awper"
                        },
                        new
                        {
                            Id = 14,
                            DateAdded = new DateTime(2023, 10, 2, 18, 11, 33, 588, DateTimeKind.Utc).AddTicks(9320),
                            DateUpdated = new DateTime(2023, 10, 2, 18, 11, 33, 588, DateTimeKind.Utc).AddTicks(9321),
                            Name = "Combat Support"
                        },
                        new
                        {
                            Id = 15,
                            DateAdded = new DateTime(2023, 10, 2, 18, 11, 33, 588, DateTimeKind.Utc).AddTicks(9322),
                            DateUpdated = new DateTime(2023, 10, 2, 18, 11, 33, 588, DateTimeKind.Utc).AddTicks(9322),
                            Name = "Medic"
                        },
                        new
                        {
                            Id = 16,
                            DateAdded = new DateTime(2023, 10, 2, 18, 11, 33, 588, DateTimeKind.Utc).AddTicks(9323),
                            DateUpdated = new DateTime(2023, 10, 2, 18, 11, 33, 588, DateTimeKind.Utc).AddTicks(9323),
                            Name = "Assault"
                        },
                        new
                        {
                            Id = 17,
                            DateAdded = new DateTime(2023, 10, 2, 18, 11, 33, 588, DateTimeKind.Utc).AddTicks(9324),
                            DateUpdated = new DateTime(2023, 10, 2, 18, 11, 33, 588, DateTimeKind.Utc).AddTicks(9325),
                            Name = "Recon"
                        },
                        new
                        {
                            Id = 18,
                            DateAdded = new DateTime(2023, 10, 2, 18, 11, 33, 588, DateTimeKind.Utc).AddTicks(9326),
                            DateUpdated = new DateTime(2023, 10, 2, 18, 11, 33, 588, DateTimeKind.Utc).AddTicks(9326),
                            Name = "Friendly"
                        },
                        new
                        {
                            Id = 19,
                            DateAdded = new DateTime(2023, 10, 2, 18, 11, 33, 588, DateTimeKind.Utc).AddTicks(9327),
                            DateUpdated = new DateTime(2023, 10, 2, 18, 11, 33, 588, DateTimeKind.Utc).AddTicks(9327),
                            Name = "Funny"
                        },
                        new
                        {
                            Id = 20,
                            DateAdded = new DateTime(2023, 10, 2, 18, 11, 33, 588, DateTimeKind.Utc).AddTicks(9328),
                            DateUpdated = new DateTime(2023, 10, 2, 18, 11, 33, 588, DateTimeKind.Utc).AddTicks(9329),
                            Name = "Serious"
                        },
                        new
                        {
                            Id = 21,
                            DateAdded = new DateTime(2023, 10, 2, 18, 11, 33, 588, DateTimeKind.Utc).AddTicks(9330),
                            DateUpdated = new DateTime(2023, 10, 2, 18, 11, 33, 588, DateTimeKind.Utc).AddTicks(9330),
                            Name = "e-Girl"
                        },
                        new
                        {
                            Id = 22,
                            DateAdded = new DateTime(2023, 10, 2, 18, 11, 33, 588, DateTimeKind.Utc).AddTicks(9331),
                            DateUpdated = new DateTime(2023, 10, 2, 18, 11, 33, 588, DateTimeKind.Utc).AddTicks(9331),
                            Name = "Silent"
                        },
                        new
                        {
                            Id = 23,
                            DateAdded = new DateTime(2023, 10, 2, 18, 11, 33, 588, DateTimeKind.Utc).AddTicks(9332),
                            DateUpdated = new DateTime(2023, 10, 2, 18, 11, 33, 588, DateTimeKind.Utc).AddTicks(9333),
                            Name = "Carry"
                        });
                });

            modelBuilder.Entity("BattleCottage.Core.Entities.GameStyle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateAdded")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("GameStyles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DateAdded = new DateTime(2023, 10, 2, 18, 11, 33, 588, DateTimeKind.Utc).AddTicks(9283),
                            DateUpdated = new DateTime(2023, 10, 2, 18, 11, 33, 588, DateTimeKind.Utc).AddTicks(9284),
                            Name = "Casual"
                        },
                        new
                        {
                            Id = 2,
                            DateAdded = new DateTime(2023, 10, 2, 18, 11, 33, 588, DateTimeKind.Utc).AddTicks(9285),
                            DateUpdated = new DateTime(2023, 10, 2, 18, 11, 33, 588, DateTimeKind.Utc).AddTicks(9285),
                            Name = "Competitive"
                        });
                });

            modelBuilder.Entity("BattleCottage.Core.Entities.LfgPost", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateAdded")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("DurationInMinutes")
                        .HasColumnType("integer");

                    b.Property<int>("GameId")
                        .HasColumnType("integer");

                    b.Property<int>("GameModeId")
                        .HasColumnType("integer");

                    b.Property<int>("GameStyleId")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.HasIndex("GameModeId");

                    b.HasIndex("GameStyleId");

                    b.HasIndex("UserId");

                    b.ToTable("LfgPosts");
                });

            modelBuilder.Entity("BattleCottage.Core.Entities.LfgPostGameRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateAdded")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("GameRoleId")
                        .HasColumnType("integer");

                    b.Property<int>("LfgPostId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("GameRoleId");

                    b.HasIndex("LfgPostId");

                    b.ToTable("LfgPostGameRoles");
                });

            modelBuilder.Entity("BattleCottage.Core.Entities.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("text");

                    b.Property<DateTime>("RefreshTokenExpiryTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("BattleCottage.Core.Entities.LfgPost", b =>
                {
                    b.HasOne("BattleCottage.Core.Entities.Game", "Game")
                        .WithMany("LfgPosts")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BattleCottage.Core.Entities.GameMode", "GameMode")
                        .WithMany("LfgPosts")
                        .HasForeignKey("GameModeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BattleCottage.Core.Entities.GameStyle", "GameStyle")
                        .WithMany("LfgPosts")
                        .HasForeignKey("GameStyleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BattleCottage.Core.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");

                    b.Navigation("GameMode");

                    b.Navigation("GameStyle");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BattleCottage.Core.Entities.LfgPostGameRole", b =>
                {
                    b.HasOne("BattleCottage.Core.Entities.GameRole", "GameRole")
                        .WithMany("LfgPostGameRoles")
                        .HasForeignKey("GameRoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BattleCottage.Core.Entities.LfgPost", "LfgPost")
                        .WithMany("LfgPostGameRoles")
                        .HasForeignKey("LfgPostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GameRole");

                    b.Navigation("LfgPost");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("BattleCottage.Core.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("BattleCottage.Core.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BattleCottage.Core.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("BattleCottage.Core.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BattleCottage.Core.Entities.Game", b =>
                {
                    b.Navigation("LfgPosts");
                });

            modelBuilder.Entity("BattleCottage.Core.Entities.GameMode", b =>
                {
                    b.Navigation("LfgPosts");
                });

            modelBuilder.Entity("BattleCottage.Core.Entities.GameRole", b =>
                {
                    b.Navigation("LfgPostGameRoles");
                });

            modelBuilder.Entity("BattleCottage.Core.Entities.GameStyle", b =>
                {
                    b.Navigation("LfgPosts");
                });

            modelBuilder.Entity("BattleCottage.Core.Entities.LfgPost", b =>
                {
                    b.Navigation("LfgPostGameRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
