// <auto-generated />
using System;
using BattleCottage.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BattleCottage.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BattleCottage.Core.Entities.Game", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("BackgroundImage")
                        .HasColumnType("text");

                    b.Property<DateTime>("DateAdded")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Games");
                });

            modelBuilder.Entity("BattleCottage.Core.Entities.GameMode", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateAdded")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("GameModes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DateAdded = new DateTime(2023, 10, 4, 18, 44, 11, 107, DateTimeKind.Utc).AddTicks(8904),
                            DateUpdated = new DateTime(2023, 10, 4, 18, 44, 11, 107, DateTimeKind.Utc).AddTicks(8904),
                            Name = "PvP"
                        },
                        new
                        {
                            Id = 2,
                            DateAdded = new DateTime(2023, 10, 4, 18, 44, 11, 107, DateTimeKind.Utc).AddTicks(8905),
                            DateUpdated = new DateTime(2023, 10, 4, 18, 44, 11, 107, DateTimeKind.Utc).AddTicks(8905),
                            Name = "PvE"
                        });
                });

            modelBuilder.Entity("BattleCottage.Core.Entities.GameRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateAdded")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("GameRoles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DateAdded = new DateTime(2023, 10, 4, 18, 44, 11, 107, DateTimeKind.Utc).AddTicks(9062),
                            DateUpdated = new DateTime(2023, 10, 4, 18, 44, 11, 107, DateTimeKind.Utc).AddTicks(9063),
                            Name = "Tank"
                        },
                        new
                        {
                            Id = 2,
                            DateAdded = new DateTime(2023, 10, 4, 18, 44, 11, 107, DateTimeKind.Utc).AddTicks(9064),
                            DateUpdated = new DateTime(2023, 10, 4, 18, 44, 11, 107, DateTimeKind.Utc).AddTicks(9064),
                            Name = "Healer"
                        },
                        new
                        {
                            Id = 3,
                            DateAdded = new DateTime(2023, 10, 4, 18, 44, 11, 107, DateTimeKind.Utc).AddTicks(9065),
                            DateUpdated = new DateTime(2023, 10, 4, 18, 44, 11, 107, DateTimeKind.Utc).AddTicks(9065),
                            Name = "DPS"
                        },
                        new
                        {
                            Id = 4,
                            DateAdded = new DateTime(2023, 10, 4, 18, 44, 11, 107, DateTimeKind.Utc).AddTicks(9066),
                            DateUpdated = new DateTime(2023, 10, 4, 18, 44, 11, 107, DateTimeKind.Utc).AddTicks(9067),
                            Name = "Top Lane"
                        },
                        new
                        {
                            Id = 5,
                            DateAdded = new DateTime(2023, 10, 4, 18, 44, 11, 107, DateTimeKind.Utc).AddTicks(9068),
                            DateUpdated = new DateTime(2023, 10, 4, 18, 44, 11, 107, DateTimeKind.Utc).AddTicks(9068),
                            Name = "Bottom Lane"
                        },
                        new
                        {
                            Id = 6,
                            DateAdded = new DateTime(2023, 10, 4, 18, 44, 11, 107, DateTimeKind.Utc).AddTicks(9069),
                            DateUpdated = new DateTime(2023, 10, 4, 18, 44, 11, 107, DateTimeKind.Utc).AddTicks(9069),
                            Name = "Mid Lane"
                        },
                        new
                        {
                            Id = 7,
                            DateAdded = new DateTime(2023, 10, 4, 18, 44, 11, 107, DateTimeKind.Utc).AddTicks(9070),
                            DateUpdated = new DateTime(2023, 10, 4, 18, 44, 11, 107, DateTimeKind.Utc).AddTicks(9071),
                            Name = "Jungle"
                        },
                        new
                        {
                            Id = 8,
                            DateAdded = new DateTime(2023, 10, 4, 18, 44, 11, 107, DateTimeKind.Utc).AddTicks(9072),
                            DateUpdated = new DateTime(2023, 10, 4, 18, 44, 11, 107, DateTimeKind.Utc).AddTicks(9072),
                            Name = "Support"
                        },
                        new
                        {
                            Id = 9,
                            DateAdded = new DateTime(2023, 10, 4, 18, 44, 11, 107, DateTimeKind.Utc).AddTicks(9073),
                            DateUpdated = new DateTime(2023, 10, 4, 18, 44, 11, 107, DateTimeKind.Utc).AddTicks(9073),
                            Name = "Entry Fragger"
                        },
                        new
                        {
                            Id = 10,
                            DateAdded = new DateTime(2023, 10, 4, 18, 44, 11, 107, DateTimeKind.Utc).AddTicks(9074),
                            DateUpdated = new DateTime(2023, 10, 4, 18, 44, 11, 107, DateTimeKind.Utc).AddTicks(9075),
                            Name = "ReFragger"
                        },
                        new
                        {
                            Id = 11,
                            DateAdded = new DateTime(2023, 10, 4, 18, 44, 11, 107, DateTimeKind.Utc).AddTicks(9075),
                            DateUpdated = new DateTime(2023, 10, 4, 18, 44, 11, 107, DateTimeKind.Utc).AddTicks(9076),
                            Name = "Strategy Caller"
                        },
                        new
                        {
                            Id = 12,
                            DateAdded = new DateTime(2023, 10, 4, 18, 44, 11, 107, DateTimeKind.Utc).AddTicks(9077),
                            DateUpdated = new DateTime(2023, 10, 4, 18, 44, 11, 107, DateTimeKind.Utc).AddTicks(9077),
                            Name = "Lurker"
                        },
                        new
                        {
                            Id = 13,
                            DateAdded = new DateTime(2023, 10, 4, 18, 44, 11, 107, DateTimeKind.Utc).AddTicks(9078),
                            DateUpdated = new DateTime(2023, 10, 4, 18, 44, 11, 107, DateTimeKind.Utc).AddTicks(9078),
                            Name = "Awper"
                        },
                        new
                        {
                            Id = 14,
                            DateAdded = new DateTime(2023, 10, 4, 18, 44, 11, 107, DateTimeKind.Utc).AddTicks(9079),
                            DateUpdated = new DateTime(2023, 10, 4, 18, 44, 11, 107, DateTimeKind.Utc).AddTicks(9080),
                            Name = "Combat Support"
                        },
                        new
                        {
                            Id = 15,
                            DateAdded = new DateTime(2023, 10, 4, 18, 44, 11, 107, DateTimeKind.Utc).AddTicks(9081),
                            DateUpdated = new DateTime(2023, 10, 4, 18, 44, 11, 107, DateTimeKind.Utc).AddTicks(9081),
                            Name = "Medic"
                        },
                        new
                        {
                            Id = 16,
                            DateAdded = new DateTime(2023, 10, 4, 18, 44, 11, 107, DateTimeKind.Utc).AddTicks(9082),
                            DateUpdated = new DateTime(2023, 10, 4, 18, 44, 11, 107, DateTimeKind.Utc).AddTicks(9082),
                            Name = "Assault"
                        },
                        new
                        {
                            Id = 17,
                            DateAdded = new DateTime(2023, 10, 4, 18, 44, 11, 107, DateTimeKind.Utc).AddTicks(9083),
                            DateUpdated = new DateTime(2023, 10, 4, 18, 44, 11, 107, DateTimeKind.Utc).AddTicks(9084),
                            Name = "Recon"
                        },
                        new
                        {
                            Id = 18,
                            DateAdded = new DateTime(2023, 10, 4, 18, 44, 11, 107, DateTimeKind.Utc).AddTicks(9085),
                            DateUpdated = new DateTime(2023, 10, 4, 18, 44, 11, 107, DateTimeKind.Utc).AddTicks(9085),
                            Name = "Friendly"
                        },
                        new
                        {
                            Id = 19,
                            DateAdded = new DateTime(2023, 10, 4, 18, 44, 11, 107, DateTimeKind.Utc).AddTicks(9086),
                            DateUpdated = new DateTime(2023, 10, 4, 18, 44, 11, 107, DateTimeKind.Utc).AddTicks(9086),
                            Name = "Funny"
                        },
                        new
                        {
                            Id = 20,
                            DateAdded = new DateTime(2023, 10, 4, 18, 44, 11, 107, DateTimeKind.Utc).AddTicks(9087),
                            DateUpdated = new DateTime(2023, 10, 4, 18, 44, 11, 107, DateTimeKind.Utc).AddTicks(9088),
                            Name = "Serious"
                        },
                        new
                        {
                            Id = 21,
                            DateAdded = new DateTime(2023, 10, 4, 18, 44, 11, 107, DateTimeKind.Utc).AddTicks(9089),
                            DateUpdated = new DateTime(2023, 10, 4, 18, 44, 11, 107, DateTimeKind.Utc).AddTicks(9089),
                            Name = "e-Girl"
                        },
                        new
                        {
                            Id = 22,
                            DateAdded = new DateTime(2023, 10, 4, 18, 44, 11, 107, DateTimeKind.Utc).AddTicks(9090),
                            DateUpdated = new DateTime(2023, 10, 4, 18, 44, 11, 107, DateTimeKind.Utc).AddTicks(9090),
                            Name = "Silent"
                        },
                        new
                        {
                            Id = 23,
                            DateAdded = new DateTime(2023, 10, 4, 18, 44, 11, 107, DateTimeKind.Utc).AddTicks(9091),
                            DateUpdated = new DateTime(2023, 10, 4, 18, 44, 11, 107, DateTimeKind.Utc).AddTicks(9091),
                            Name = "Carry"
                        });
                });

            modelBuilder.Entity("BattleCottage.Core.Entities.GameStyle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateAdded")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("GameStyles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DateAdded = new DateTime(2023, 10, 4, 18, 44, 11, 107, DateTimeKind.Utc).AddTicks(9047),
                            DateUpdated = new DateTime(2023, 10, 4, 18, 44, 11, 107, DateTimeKind.Utc).AddTicks(9048),
                            Name = "Casual"
                        },
                        new
                        {
                            Id = 2,
                            DateAdded = new DateTime(2023, 10, 4, 18, 44, 11, 107, DateTimeKind.Utc).AddTicks(9049),
                            DateUpdated = new DateTime(2023, 10, 4, 18, 44, 11, 107, DateTimeKind.Utc).AddTicks(9049),
                            Name = "Competitive"
                        });
                });

            modelBuilder.Entity("BattleCottage.Core.Entities.LFGPost", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateAdded")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("DurationInMinutes")
                        .HasColumnType("integer");

                    b.Property<int>("GameId")
                        .HasColumnType("integer");

                    b.Property<int>("GameModeId")
                        .HasColumnType("integer");

                    b.Property<int>("GameStyleId")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.HasIndex("GameModeId");

                    b.HasIndex("GameStyleId");

                    b.HasIndex("UserId");

                    b.ToTable("LFGPosts");
                });

            modelBuilder.Entity("BattleCottage.Core.Entities.LFGPostGameRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateAdded")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("GameRoleId")
                        .HasColumnType("integer");

                    b.Property<int>("LFGPostId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("GameRoleId");

                    b.HasIndex("LFGPostId");

                    b.ToTable("LFGPostGameRoles");
                });

            modelBuilder.Entity("BattleCottage.Core.Entities.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("text");

                    b.Property<DateTime>("RefreshTokenExpiryTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("BattleCottage.Core.Entities.LFGPost", b =>
                {
                    b.HasOne("BattleCottage.Core.Entities.Game", "Game")
                        .WithMany("LFGPosts")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BattleCottage.Core.Entities.GameMode", "GameMode")
                        .WithMany("LFGPosts")
                        .HasForeignKey("GameModeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BattleCottage.Core.Entities.GameStyle", "GameStyle")
                        .WithMany("LFGPosts")
                        .HasForeignKey("GameStyleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BattleCottage.Core.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");

                    b.Navigation("GameMode");

                    b.Navigation("GameStyle");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BattleCottage.Core.Entities.LFGPostGameRole", b =>
                {
                    b.HasOne("BattleCottage.Core.Entities.GameRole", "GameRole")
                        .WithMany("LFGPostGameRoles")
                        .HasForeignKey("GameRoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BattleCottage.Core.Entities.LFGPost", "LFGPost")
                        .WithMany("LFGPostGameRoles")
                        .HasForeignKey("LFGPostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GameRole");

                    b.Navigation("LFGPost");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("BattleCottage.Core.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("BattleCottage.Core.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BattleCottage.Core.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("BattleCottage.Core.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BattleCottage.Core.Entities.Game", b =>
                {
                    b.Navigation("LFGPosts");
                });

            modelBuilder.Entity("BattleCottage.Core.Entities.GameMode", b =>
                {
                    b.Navigation("LFGPosts");
                });

            modelBuilder.Entity("BattleCottage.Core.Entities.GameRole", b =>
                {
                    b.Navigation("LFGPostGameRoles");
                });

            modelBuilder.Entity("BattleCottage.Core.Entities.GameStyle", b =>
                {
                    b.Navigation("LFGPosts");
                });

            modelBuilder.Entity("BattleCottage.Core.Entities.LFGPost", b =>
                {
                    b.Navigation("LFGPostGameRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
